### ISSUE TITLE
Wrong shebangs and spurious executable bits

### ISSUE THREAD

**Issue by Enchufa2** [kcf-jackson/sketch#17]
RPM-based build systems have checks of this kind, and they are being triggered for the files under `inst`. See the [build log](https://download.copr.fedorainfracloud.org/results/iucar/cran/fedora-37-x86_64/04856298-R-CRAN-sketch/builder-live.log.gz):

```
+ /usr/lib/rpm/redhat/brp-mangle-shebangs
*** WARNING: ./usr/local/lib/R/library/sketch/test_files/test_R6.R is executable but has no shebang, removing executable bit
*** WARNING: ./usr/local/lib/R/library/sketch/test_files/test_R6.js is executable but has no shebang, removing executable bit
*** WARNING: ./usr/local/lib/R/library/sketch/test_files/test_R6_2.R is executable but has no shebang, removing executable bit
*** WARNING: ./usr/local/lib/R/library/sketch/test_files/test_R6_2.js is executable but has no shebang, removing executable bit
*** ERROR: ./usr/local/lib/R/library/sketch/test_files/test_R6_3.R has shebang which doesn't start with '/' (config(debug = TRUE))
...
```

etc. Please, consider removing the executable bit and also the `#!` on top of some of these files. My understanding is that this could be a regular comment (without the exclamation).

**Comment by kcf-jackson** [comment]
Thanks for reporting the issue and sending through the build log. 

Could you please clarify how the .R and .js files become executable? As far as I know, they do not contain executable bits. They would work only if you run the scripts through the R interpreter or JavaScript interpreter. I have reviewed the files listed in the log, and I am not sure what to remove. For example, here is the full content from [`test_files/test_R6.R`](https://github.com/kcf-jackson/sketch/blob/master/inst/test_files/test_R6.R):

```
Person <- R6Class("Person", list(
  name = JS_NULL,
  age = JS_NULL,
  initialize = function(name, age) {
    self$name <- name
    self$age <- age
  }
))
eva <- Person$new("Eva", 6)
print(eva$name)
print(eva$age)
```
I see no shebang and no external calls.

You are right that the lines starting with `#!` (with or without the exclamation) are regular R comments. The shebang operators are special instructions for the transpiler, and it would fail to work if they are removed.

**Comment by Enchufa2** [comment]
> You are right that the lines starting with `#!` (with or without the exclamation) are regular R comments. The shebang operators are special instructions for the transpiler, and it would fail to work if they are removed.

Wait, I didn't see this part. What's the "transpiler"?

**Comment by Enchufa2** [comment]
I repurposed the PR to just remove the executable flag from the files. But unfortunately those ones only raise warnings. The non-shebangs are the ones that actually make the building process fail, so my recommendation would be to reconsider this choice.

**Comment by kcf-jackson** [comment]
Thanks for the follow-up and the PR.

If I understand you correctly, the cause of the problem is that `/usr/lib/rpm/redhat/brp-mangle-shebangs` scanned the package files, interpreted the R comments as script instructions, and triggered the warnings. And you are suggesting to switch to a different character for the special instructions to avoid confusing `brp-mangle-shebangs`. 

It sounds sensible to me to support `#!` for backward compatibility and move to a new character that do not break build processes. I will evaluate this option, and if viable, I will make the change in the next update.

**Comment by Enchufa2** [comment]
Thanks for your consideration! Nice package, BTW!

**Comment by kcf-jackson** [comment]
Following up on the issue,

- The new directive `#|` has been added (with `#!` continuing to work for backward compatibility).  
- All the test files in the package have been updated to use the new directive. 
- The update has been accepted on CRAN. The version is bumped up to 1.1.19.

I hope this will fix the issue with the build process. Thanks.

**Comment by Enchufa2** [comment]
It builds fine now, thanks!
