### ISSUE TITLE
[Feedback needed] 'var' or not 

### ISSUE THREAD

**Issue by kcf-jackson** [kcf-jackson/sketch#6]
Currently, the sketch package uses `let` and `const` for variable declarations,  as they are preferred over `var` in the JavaScript community. `let` and `const` follow the block-scoping rule, so it is easier to reason with them compared with `var`, which triggers a behaviour known as hoisting.

While the fact that `let` and `const` are explicit is considered as a good thing in JavaScript, it could feel unnatural to R users as R takes care of variable declaration automatically. I am thinking if sketch should use the `var` keyword for assignment.  The proposal is to:

- turn all assignments `variable <- value` into `var variable = value`, and 
- leave all super-assignments `variable <<- value` as `variable = value`.

This should eliminate the need to define variables before use. In the [post](https://softwareengineering.stackexchange.com/a/274352), it was mentioned "`var` might possibly still be useful in an extreme case like machine-generated code, but I'm stretching hard there".  The extreme case referred is exactly the case here in sketch. The drawback, however, is that there may be some edge cases that cannot be resolved if `var` is assumed everywhere. (Though the counter examples given in the post won't be a problem in sketch because for loop always uses `let` regardless of the declaration rules, and it makes no sense in R to have two values binded to the same variable under the same environment.) 

Potentially, I could create a custom deparser so that users can pick either behaviour, but I wonder what would users / developers want as default as this would affect all the tutorials I am working on right now. Could watchers of this repo and @JohnCoene give some feedback on this? Thanks.

**Comment by JohnCoene** [comment]
Sorry for the late response to this. What you propose makes sense to me. 

Although variables don't have to be declared in R, to the best of my knowledge R users nonetheless understand scoping rules (probably not directly).

```r
x <- 1

print_x <- function(){
  print(x)
}

print_x()
```

Though the above works in R it's never used (for good reasons). I think the logic you propose makes sense and should not cause issues for R users.

**Comment by kcf-jackson** [comment]
@JohnCoene Thanks for the feedback. The (optional) feature is now available under the `develop` branch using `basic_2_rules`/`default_2_rules` and `default_2_deparsers` for the `rules` and `deparsers` arguments in  `compile_r`. (Perhaps, a better naming convention is needed.)

Here is a minimal example:
#### main.R
```
add <- function(x, y) {
    a <- x + y
    a
}
```

Using the command `compile_r("main.R", rules = basic_2_rules(), deparsers = default_2_deparsers())` gives
```
var add = function(x, y) {
    var a = x + y
    return a
}
```

As an R user, it does feel more natural not needing to worry about explicit return and variable declaration, and likely this will be the default for the tutorials. 

As a side note, the automatic return only applies to variables / values but not expressions (e.g. if-statement, for-loop). This is a behaviour of JavaScript, and the transpiler will issue a warning when it sees a function that ends with an expression. 

<hr>

For comparison purposes, here is an example using the original `basic_rules`/`default_rules` and `default_deparsers` (which continue to be supported). Under this setting, all declarations and returns need to be explicit. (The style is more JavaScript-like.)

#### main.R
```
add <- function(x, y) {
    let (a = x + y)
    return(a)
}
```

Using the command `compile_r("main.R", rules = basic_rules(), deparsers = default_deparsers())` gives
```
add = function(x, y) {
    let a = x + y
    return(a)
}
```
The difference between the two conventions seems little, but from experience, it is easy to miss an explicit return or variable declaration here and there, and finding them is such a time sink!
